# Generated by Django 4.2.8 on 2024-05-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genreId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OTTPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platformId', models.IntegerField()),
                ('logopath', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Disney',
        ),
        migrations.DeleteModel(
            name='Netflix',
        ),
        migrations.DeleteModel(
            name='Watcha',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre_ids',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='provider_id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='movies.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ott_platforms',
            field=models.ManyToManyField(related_name='movies', to='movies.ottplatform'),
        ),
    ]
