# Generated by Django 4.2.8 on 2024-05-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0002_movie_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_movies', to='accounts.userinfo'),
        ),
    ]
