# Generated by Django 4.2.8 on 2024-05-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_generatedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedImage',
        ),
    ]
