# Generated by Django 4.2.8 on 2024-05-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='selectedmovies',
            new_name='selectedMovies',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='selectedotts',
            new_name='selectedOtts',
        ),
    ]
