# Generated by Django 4.2.8 on 2024-05-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinfo_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(blank=True, default='profile/default.png', upload_to='profile/'),
        ),
    ]
